### PR TITLE
Adds starred repository count and adds links on bio

### PR DESCRIPTION
**Pull request by IordanisKostelidis**
Hello, i participate in "Hacktoberfest" and i saw your project. It's very cool and i wanted to contribute.

In this PR i have changed the following:

- Added some missing pair dependencies
- Refactored the code (fix react compiler warnings)
- Added starred repositories total count (graphQL, resume view)
- Added support for links in bio
- Refactored the repository ownership check
- All stats label to start with uppercase char (for example, from: followers to: Followers)

I attach a screenshot of the new resume.
Github Resume Generator

### CODE REVIEW

**Comment by Satyam1203** [comment]
Cool @IordanisKostelidis , I really liked that you focused on small issues like parsing bio, adding starred repositories, avoiding README repo to appear in repo list, etc. 

PS: I prefer to have npm over yarn as package manager

**Comment by IordanisKostelidis** [comment]
@Satyam1203 Ok,if you want, i can create a new PR without change the package manager.

**Comment by Satyam1203** [comment]
@IordanisKostelidis  That would be great, if you can create a new PR with npm as package manager.

**Comment by IordanisKostelidis** [comment]
@Satyam1203 I updated this PR (removes the yarn.lock, rollback to package.json and package-lock.json and adds the typescript missing pair for tsutils@3.17.1 and the subscriptions-transport-ws missing pair for @apollo/client@3.1.3)

**Comment by IordanisKostelidis** [comment]
@Satyam1203 I updated this PR (removes the yarn.lock, rollback to package.json and package-lock.json and adds the typescript missing pair for tsutils@3.17.1 and the subscriptions-transport-ws missing pair for @apollo/client@3.1.3)

**Comment by Satyam1203** [comment]
Okay.. great

**Pull request merged**
